### ISSUE TITLE
Improved looks/styling ability?

### ISSUE THREAD

**Issue by jrencz** [OussamaRomdhane/storybook-addon-datalayer-watcher#1]
Hi,

since I'm the first issue author let me say: **thank you for a very nice add-on!**
I just integrated it with my storybook and it works very nice.

Have you considered making it possible for the user to apply own styles?
I found a way to refine it a little bit according to my preferences (i.e. so it looks more like the Actions built-in panel)

Here's my **very hacky**, yet I think safe take (by "safe" I mean - "will not cause damage in other addons' panels", but by no means "future-proof"):

```css
#storybook-panel-root:has(#tabbutton-storybook-storybook-addon-datalayer-watcher-panel.tabbutton-active) #panel-tab-content > div:not([hidden]) div:has(button) {
    height: 30px;
    padding-right: 0;
}

#storybook-panel-root:has(#tabbutton-storybook-storybook-addon-datalayer-watcher-panel.tabbutton-active) #panel-tab-content > div:not([hidden]) > div:has(button) {
    background-color: hsla(0, 0%, 100%, 0.6);
    backdrop-filter: saturate(180%) blur(5px);
}

#storybook-panel-root:has(#tabbutton-storybook-storybook-addon-datalayer-watcher-panel.tabbutton-active) #panel-tab-content > div:not([hidden]) button {
    margin: 0;
}

#storybook-panel-root:has(#tabbutton-storybook-storybook-addon-datalayer-watcher-panel.tabbutton-active) #panel-tab-content [role="tree"] {
    text-wrap: nowrap;
}

#storybook-panel-root:has(#tabbutton-storybook-storybook-addon-datalayer-watcher-panel.tabbutton-active) #panel-tab-content > div:not([hidden]) > :last-child {
    gap: 2px;
    margin: 10px 5px 20px;
}
```

This code can be injected to Manager via [`managerHead`](https://storybook.js.org/docs/api/main-config-manager-head) or [`manager-head.html`](https://storybook.js.org/docs/configure/theming#css-escape-hatches). I chose the `managerHead` myself because of those long repeated selectors. Here's my actual code:

<details>

```ts
const addonName = 'storybook-addon-datalayer-watcher';
const activeTabSelector = `#tabbutton-storybook-${addonName}-panel.tabbutton-active`;

/**
 * Matches content pf Addons Panel only if storybook-addon-datalayer-watcher is
 * active.
 */
const contentSelector = `#storybook-panel-root:has(${activeTabSelector}) #panel-tab-content`

/**
 * Styles that apply to the strip which has the "Clear dataLayer" button,
 * so it's smaller and a bit prettier
 */
// language=css
const clearButtonStyles = `
    ${contentSelector} > div:not([hidden]) div:has(button) {
        height: 30px;
        padding-right: 0;
    }

    ${contentSelector} > div:not([hidden]) > div:has(button) {
        background-color: hsla(0, 0%, 100%, 0.6);
        backdrop-filter: saturate(180%) blur(5px);
    }

    ${contentSelector} > div:not([hidden]) button {
        margin: 0;
    }
`;

/**
 * Makes events look as close to how elements in Actions look, as possible.
 */
// language=css
const eventsStyles = `
    ${contentSelector} [role="tree"] {
        text-wrap: nowrap;
    }

    ${contentSelector} > div:not([hidden]) > :last-child {
        gap: 2px;
        margin: 10px 5px 20px;
    }
`;

// language=html
export const dataLayerWatcherStylesForManagerHead = `
  <style>${
    [
      clearButtonStyles,
      eventsStyles,
    ].join('\n')
  }</style>
`;
``` 

</details>

@OussamaRomdhane are you open to making it look like that, or maybe allowing some way of applying own styles in documented and future-safe way?
